---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefed-controller-manager
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      serviceAccountName: kubefed-controller
      containers:
      - args:
        - --kubefed-namespace=$(KUBEFED_NAMESPACE)
        - -v=5
        - --logtostderr
        command:
        - /hyperfed/controller-manager
        image: quay.io/kubernetes-multicluster/kubefed:canary
        imagePullPolicy: Always
        name: controller-manager
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        env:
        - name: KUBEFED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
